name: checking out reference application
#new
on:
  push:
    branches: [ master ]   
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout  repo from philips-internal
        uses: actions/checkout@v2
          
      - name: Step 2 - Gradle wrapper version validation
        uses: gradle/wrapper-validation-action@v1
      
      - name: Step 3 - Use Java version 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          cache: gradle
                
      - name: Step 4 - Granting permissions to gradlew file
        run: chmod +x ./gradlew
                  
      - name: Step 5 - Build with Gradle
        uses: gradle/gradle-build-action@v2.1.1
        with:
          arguments: build
          #gradle-version: 4.10
          
      - name: Step 6 - Listing the build file name
        run: |
            ls '${{ github.workspace }}'
            echo "-----------------------------"
            ls '${{ github.workspace }}'/admin/build
            echo "-----------------------------"
            ls '${{ github.workspace }}'/common-model/build
            echo "-----------------------------"
            ls '${{ github.workspace }}'/dao/build
            ls '${{ github.workspace }}'/rest/build
            
